/* START */

/**
 * STEPS
 *
 * 1. DEVELOP A LIBRARY OF STATIC GRAPH
 * 2. CONSISTS OF NODES, EDGES, COST OF EDGES
 * 3. NETWORK TOPOLOGY, ROUTING PROTOCOLS, GRAPH ALGORITHMS
 * 4. GRAPH NODES ARE SIMPLE NODES FOR NOW
 * 5. NEXT STEP, NETWORK TOPOLOGY
 *
 */