/**
 * PROJECT GOALS
 *
 * 1. SET UP GENERIC GRAPH
 * 2. SET UP NETWORK TOPOLOGY
 * 3. INTEGRATE CLI
 * 4. PACKET EXCHANGE SIMULATION INFRA SETUP
 * 5. ARP, MAC FORWARDING
 * 6. ROUTE INSTLLATION, L3 ROUTING
 * 7. PING, TRACEROUTE
 */